version: '3'

services:
    node:
        build:
            context: .
            dockerfile: nodejs.dockerfile
        container_name: gusnode
        ports:
            - 80:8080
        volumes:
            - ./:/var/www/html
        networks:
            gus-node-network:
                ipv4_address: 12.0.0.10

networks:
    gus-node-network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "12.0.0.0/16"