version: '3'

services:
    node:
        build:
            context: .
            dockerfile: nodejs.dockerfile
        container_name: gusmljs
        ports:
            - 80:8080
        volumes:
            - ./:/var/www/html
        networks:
            - app-network

networks:
    app-network:
        driver: bridge